### ISSUE TITLE
Cannot download file from google drive

### ISSUE THREAD

**Issue by teone182** [snu-cdrc/dog-reference-epigenome#5]
Hello!

I would like to download a file from the google drive, but it is not possible.
The file I'm interested in is the following:

Dog_RNA_FPKM-UQ.mg.txt (through "Download: Categorized genes according to tissue specificity").

Could you make this file (and also all the other files) downloadable? 

Thank you very much in advance!

**Comment by keun-hong** [comment]
Hello,

Firstly, I apologize for the delay in responding to your message.

I checked the access permissions are set to open.

To better assist you, could you please clarify if you are experiencing difficulty accessing the Google Drive link itself, or if the issue is specifically with downloading the file "Dog_RNA_FPKM-UQ.mg.txt" once you have accessed the drive?

Looking forward to your response so that we can resolve this issue promptly.

Best regards,

Keun Hong Son

**Comment by teone182** [comment]
Hi!

Thanks for your email.

Soon after opening the issue, I managed to download the file by opening it
with another app and saving it locally, not by directly downloading.
But now I can see that the download option from the right grid is visible,
something that did not work previously.

Anyway, the issue is solved and you do not have to take any other action.

Thanks again, I appreciate it.

Kind regards,

Matteo


Il giorno gio 14 dic 2023 alle ore 19:08 Keun Hong Son <
***@***.***> ha scritto:
